FROM python:3.8
WORKDIR sp_scrapy/
COPY sp_scrapy .
RUN pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
COPY sources.list /etc/apt
RUN apt-get update \
    apt-get install nodejs --assume-yes
CMD ["python3","main.py"]